name = "mnt-smp"
mc_version = "1.21.1"

[jar]
type = "fabric"
loader = "0.18.4"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "3wZtvzew"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "sOzRw3CG"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "zsoi0dso"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "E5eJVp4O"

[[mods]]
type = "modrinth"
id = "Bh37bMuy"
version = "KoUrx3jJ"

[[mods]]
type = "modrinth"
id = "vqqx0QiE"
version = "3Smu12Iu"

[[mods]]
type = "modrinth"
id = "Es5v4eyq"
version = "RR1lyQmh"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "u1OEbNKx"

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "3wZtvzew"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "sOzRw3CG"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "zsoi0dso"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "E5eJVp4O"

[[mods]]
type = "modrinth"
id = "Bh37bMuy"
version = "KoUrx3jJ"

[[mods]]
type = "modrinth"
id = "vqqx0QiE"
version = "3Smu12Iu"

[[mods]]
type = "modrinth"
id = "Es5v4eyq"
version = "RR1lyQmh"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "u1OEbNKx"

[[mods]]
type = "modrinth"
id = "zV5r3pPn"
version = "bb8Z5elg"

[[mods]]
type = "modrinth"
id = "ir8okcEA"
version = "kPsGsZkl"

[[mods]]
type = "modrinth"
id = "defK2XM3"
version = "gDZXNqOx"

[[mods]]
type = "modrinth"
id = "YhmgMVyu"
version = "NSqdh1i9"

[[mods]]
type = "modrinth"
id = "jhl28YkY"
version = "czJc7eUX"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "b5ZiCjAr"

[[mods]]
type = "modrinth"
id = "lhGA9TYQ"
version = "Wto0RchG"

[[mods]]
type = "modrinth"
id = "BgNRHReB"
version = "TxWM7AW8"

[[mods]]
type = "modrinth"
id = "gc8OEnCC"
version = "4qhBEg6J"

[[mods]]
type = "modrinth"
id = "8shC1gFX"
version = "phATjGhF"

[[mods]]
type = "modrinth"
id = "MpzVLzy5"
version = "M1o6hR2m"

[[mods]]
type = "modrinth"
id = "HXF82T3G"
version = "YPm4arUa"

[[mods]]
type = "modrinth"
id = "zFiY2Go0"
version = "Nw12fcYg"

[[mods]]
type = "modrinth"
id = "uy4Cnpcm"
version = "eRd8PTb9"

[[mods]]
type = "modrinth"
id = "K01OU20C"
version = "nLsCe2VD"

[[mods]]
type = "modrinth"
id = "joEfVgkn"
version = "dmotghAy"

[[mods]]
type = "modrinth"
id = "gu7yAYhd"
version = "YoUTrY6U"

[[mods]]
type = "modrinth"
id = "lz0ymQav"
version = "Cgl4TjDT"

[[mods]]
type = "modrinth"
id = "t1VgucWo"
version = "gC8IvJwh"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "HpMb5wGb"

[[mods]]
type = "modrinth"
id = "SaCpeal4"
version = "LUPOTXbk"

[[mods]]
type = "modrinth"
id = "fnAffV0n"
version = "3MnQb3Tb"

[[mods]]
type = "modrinth"
id = "DNuNq5bb"
version = "khb6eZvR"

[[mods]]
type = "modrinth"
id = "QIt10I7z"
version = "Z6qzb6Wz"

[[mods]]
type = "modrinth"
id = "rYocd2LE"
version = "3dymmAXs"

[[mods]]
type = "modrinth"
id = "nWSeFpQt"
version = "xqZmCXEv"

[[mods]]
type = "modrinth"
id = "tpehi7ww"
version = "EUlNXs9V"

[[mods]]
type = "modrinth"
id = "OVuFYfre"
version = "HBZAPs3u"

[[mods]]
type = "modrinth"
id = "UVtY3ZAC"
version = "DqX0eegg"

[[mods]]
type = "modrinth"
id = "RV1qfVQ8"
version = "i1WCJNIW"

[[mods]]
type = "modrinth"
id = "Ha28R6CL"
version = "N6D3uiZF"

[[mods]]
type = "modrinth"
id = "VZCZSOio"
version = "ITaiugix"

[[mods]]
type = "modrinth"
id = "D53qveoj"
version = "MJ2OF7eg"

[[mods]]
type = "modrinth"
id = "KJe6y9Eu"
version = "2mIvRTNp"

[[mods]]
type = "modrinth"
id = "sTZr7NVo"
version = "LUSqgrjd"

[[mods]]
type = "modrinth"
id = "8BmcQJ2H"
version = "fvT8GY10"

[[mods]]
type = "modrinth"
id = "s3dmwKy5"
version = "lbSHOhee"

[[mods]]
type = "modrinth"
id = "kGP3J2TW"
version = "xWfKx36d"

[[mods]]
type = "modrinth"
id = "y9vDr4Th"
version = "5mQbcYf1"

[[mods]]
type = "modrinth"
id = "nmDcB62a"
version = "NnNX8LBn"

[[mods]]
type = "modrinth"
id = "fPetb5Kh"
version = "9W2MUsnU"

[[mods]]
type = "modrinth"
id = "WBvnqHfV"
version = "TRMapjpU"

[[mods]]
type = "modrinth"
id = "MPCX6s5C"
version = "pznwoEHz"

[[mods]]
type = "modrinth"
id = "ccKDOlHs"
version = "JB1fLQnc"

[[mods]]
type = "modrinth"
id = "tagwiZkJ"
version = "Ng5Y6KVo"

[[mods]]
type = "modrinth"
id = "J9pKOkxP"
version = "cEF2AxxA"

[[mods]]
type = "modrinth"
id = "aaRl8GiW"
version = "Ef7P6Rb7"

[[mods]]
type = "modrinth"
id = "3NCrJdj3"
version = "QtkC5plA"

[[mods]]
type = "modrinth"
id = "gnwGOmBf"
version = "Z6zil2J0"

[[mods]]
type = "modrinth"
id = "KDvYkUg3"
version = "rfFqJDcN"

[[mods]]
type = "modrinth"
id = "nfn13YXA"
version = "aWzTESNC"

[[mods]]
type = "modrinth"
id = "aTaCgKLW"
version = "jrC1TCfF"

[[mods]]
type = "modrinth"
id = "ItTQpuBn"
version = "fcg0BOwC"

[[mods]]
type = "modrinth"
id = "LN9BxssP"
version = "euSlaAtA"

[[mods]]
type = "modrinth"
id = "rOUBggPv"
version = "SZOjxftk"

[[mods]]
type = "modrinth"
id = "3eMENr4V"
version = "CNwZZ4FD"

[[mods]]
type = "modrinth"
id = "kkmrDlKT"
version = "XNtIBXyQ"

[[mods]]
type = "modrinth"
id = "8oi3bsk5"
version = "MuJMtPGQ"

[[mods]]
type = "modrinth"
id = "54eqfZSC"
version = "5A24T8JD"

[[mods]]
type = "modrinth"
id = "RJcwF5bg"
version = "azmCiYpi"

[[mods]]
type = "modrinth"
id = "rlloIFEV"
version = "i6cd1S6S"

[[mods]]
type = "modrinth"
id = "5aaWibi9"
version = "JagCscwi"

[[mods]]
type = "modrinth"
id = "kpMfA312"
version = "LGF8VScD"

[[mods]]
type = "modrinth"
id = "OhduvhIc"
version = "1NZqjOaM"

[[mods]]
type = "modrinth"
id = "OMiCHIwt"
version = "ByAkqZD1"

[[mods]]
type = "modrinth"
id = "RiN8rDVs"
version = "mPmeykPR"

[[mods]]
type = "modrinth"
id = "31zVNrFa"
version = "9fdKSEzJ"

[[mods]]
type = "modrinth"
id = "1bokaNcj"
version = "Vqkdzsyt"

[[mods]]
type = "modrinth"
id = "NcUtCpym"
version = "hT5eHHLt"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "o3cDn8Vp"

[[mods]]
type = "modrinth"
id = "Ua7DFN59"
version = "9aZPNrZC"

[[mods]]
type = "modrinth"
id = "Dfu00ggU"
version = "72UkhXm7"

[[mods]]
type = "modrinth"
id = "o1C1Dkj5"
version = "fQ7EjDPE"

[[mods]]
type = "modrinth"
id = "2BwBOmBQ"
version = "zpUYcjIg"

[[mods]]
type = "modrinth"
id = "z9Ve58Ih"
version = "uiGCmR8O"

[[mods]]
type = "modrinth"
id = "Z2mXHnxP"
version = "gxBGYcIL"

[[mods]]
type = "modrinth"
id = "3dT9sgt4"
version = "TGK6gpeO"

[[mods]]
type = "modrinth"
id = "kidLKymU"
version = "uYZShp1p"

[[mods]]
type = "modrinth"
id = "t5FRdP87"
version = "bdpPtvTn"

[[mods]]
type = "modrinth"
id = "cs7iGVq1"
version = "geZa9lJS"

[[mods]]
type = "modrinth"
id = "w7ThoJFB"
version = "WmVN03jQ"

[[mods]]
type = "modrinth"
id = "x3HZvrj6"
version = "zxxPmIks"

[[mods]]
type = "modrinth"
id = "uNRoUnGT"
version = "ZYE0xW87"

[[mods]]
type = "modrinth"
id = "Y8TA5POy"
version = "8e3GJKd9"

[[mods]]
type = "modrinth"
id = "b1ZV3DIJ"
version = "7PcGW9Vp"

[[mods]]
type = "modrinth"
id = "ftdbN0KK"
version = "hjhT2sMz"

[[mods]]
type = "modrinth"
id = "Q5HY7g5g"
version = "Y6DCSenJ"

[[mods]]
type = "modrinth"
id = "XkisZUfp"
version = "mNh9iuNi"

[[mods]]
type = "modrinth"
id = "DZV7EZ2D"
version = "emxkbvxS"

[[mods]]
type = "modrinth"
id = "xv94TkTM"
version = "hGJDoW2W"

[[mods]]
type = "modrinth"
id = "btPzz1Xc"
version = "TDOCHRl8"

[[mods]]
type = "modrinth"
id = "h3XWIuzM"
version = "HLjyJHzA"

[[mods]]
type = "modrinth"
id = "CkqTAIaP"
version = "17SqiDCk"

[[mods]]
type = "modrinth"
id = "JcIgEOzn"
version = "PTlFA1ut"

[[mods]]
type = "modrinth"
id = "ohNO6lps"
version = "N5qzq0XV"

[[mods]]
type = "modrinth"
id = "uHWrqYcS"
version = "Th1NMMIZ"

[[mods]]
type = "modrinth"
id = "g3jBz897"
version = "a6yaUdIf"

[[mods]]
type = "modrinth"
id = "huOhn9zP"
version = "4o9rF2gI"

[[mods]]
type = "modrinth"
id = "oRgKGxhT"
version = "TJ0gIh5X"

[[mods]]
type = "modrinth"
id = "D5h9NKNI"
version = "gdB0WW0x"

[[mods]]
type = "modrinth"
id = "mOgUt4GM"
version = "YIfqIJ8q"

[[mods]]
type = "modrinth"
id = "9KZOe6HD"
version = "3oUjHjM8"

[[mods]]
type = "modrinth"
id = "4sYI62kA"
version = "1aXJP4f8"

[[mods]]
type = "modrinth"
id = "eXts2L7r"
version = "U5bhVym2"

[[mods]]
type = "modrinth"
id = "ZmmmAZp7"
version = "U8dtUjDy"

[[mods]]
type = "modrinth"
id = "QAGBst4M"
version = "L007zH3l"

[[mods]]
type = "modrinth"
id = "fuuu3xnx"
version = "tRdr8Bg3"

[[mods]]
type = "modrinth"
id = "ngBlYV53"
version = "qA8BwJL7"

[[mods]]
type = "modrinth"
id = "Z7LQgxZt"
version = "ZGxJ3GPf"

[[mods]]
type = "modrinth"
id = "nCk7Sfz8"
version = "h2udQFX8"

[[mods]]
type = "modrinth"
id = "6nHZTTjQ"
version = "xhubN5q0"

[[mods]]
type = "modrinth"
id = "6AQIaxuO"
version = "j4ao0meG"

[[mods]]
type = "modrinth"
id = "chat-heads"
version = "9dRmYosQ"

[[mods]]
type = "modrinth"
id = "clumps"
version = "3ene3W1l"

[[mods]]
type = "modrinth"
id = "ambientsounds"
version = "ZNs2dkwo"

[[mods]]
type = "modrinth"
id = "c2me-fabric"
version = "DSqOVCaF"

[[mods]]
type = "modrinth"
id = "visuality"
version = "dhKbgdIb"

[[mods]]
type = "modrinth"
id = "visual-workbench"
version = "fGXmFJ8q"

[[mods]]
type = "modrinth"
id = "capes"
version = "6SzVPVR4"

[[mods]]
type = "modrinth"
id = "morechathistory"
version = "3siYJiWG"

[[mods]]
type = "modrinth"
id = "mixintrace"
version = "LGYOH4RN"

[[mods]]
type = "modrinth"
id = "handcrafted"
version = "f0pKpUWd"

[[mods]]
type = "modrinth"
id = "rrls"
version = "FDyKvCJ2"

[[mods]]
type = "modrinth"
id = "bobby"
version = "oeSOphtG"

[[mods]]
type = "modrinth"
id = "lootr"
version = "SEy2jzxJ"

[[mods]]
type = "modrinth"
id = "terralith"
version = "MuJMtPGQ"

[[mods]]
type = "modrinth"
id = "comforts"
version = "LUPOTXbk"

[[mods]]
type = "modrinth"
id = "chipped"
version = "6h2mVZcb"

[[mods]]
type = "modrinth"
id = "spark"
version = "cALUj9l1"

[[mods]]
type = "modrinth"
id = "wavey-capes"
version = "ZtvlEp9r"

[[mods]]
type = "modrinth"
id = "freecam"
version = "Cg10zLnR"

[[mods]]
type = "modrinth"
id = "advancement-plaques"
version = "g0SNjiMq"

[[mods]]
type = "modrinth"
id = "chatanimation"
version = "mezhyzfP"

[[mods]]
type = "modrinth"
id = "what-are-they-up-to"
version = "iHAQTK0N"

[[mods]]
type = "modrinth"
id = "resourceful-lib"
version = "Hf91FuVF"

[[mods]]
type = "modrinth"
id = "moonlight"
version = "SyIbV8py"

[[mods]]
type = "modrinth"
id = "coroutil"
version = "U0NUocji"

[[mods]]
type = "modrinth"
id = "creativecore"
version = "3ZRFwsQm"

[[mods]]
type = "modrinth"
id = "iceberg"
version = "7ITFAyW8"

[[mods]]
type = "modrinth"
id = "pneumono_gravestones"
version = "qht7ppsj"

[[mods]]
type = "modrinth"
id = "pneumono_core"
version = "QKvgjhTZ"

[[mods]]
type = "modrinth"
id = "tesseract"
version = "9L9uix4F"

[[mods]]
type = "modrinth"
id = "energized-power"
version = "lQ3T62Ud"

[[mods]]
type = "modrinth"
id = "energized-power-bop"
version = "oso40B1G"

[[mods]]
type = "modrinth"
id = "energized-power-ta"
version = "dIQQn9UV"

[[mods]]
type = "modrinth"
id = "new-linked-chests"
version = "hYiFHtv0"

[[mods]]
type = "modrinth"
id = "extravaganza"
version = "UbLfCVsi"
