name = "mnt-smp"
mc_version = "1.21.1"

[jar]
type = "fabric"
loader = "0.18.4"
installer = "latest"

[variables]
SERVER_PORT = "25565"

[launcher]
eula_args = true
nogui = true

[markdown]
files = ["README.md"]
auto_update = false

[options]
success_line = ""
stop_command = ""

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "3wZtvzew"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "sOzRw3CG"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "zsoi0dso"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "E5eJVp4O"

[[mods]]
type = "modrinth"
id = "Bh37bMuy"
version = "KoUrx3jJ"

[[mods]]
type = "modrinth"
id = "vqqx0QiE"
version = "3Smu12Iu"

[[mods]]
type = "modrinth"
id = "Es5v4eyq"
version = "RR1lyQmh"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "u1OEbNKx"

[[mods]]
type = "modrinth"
id = "P7dR8mSH"
version = "3wZtvzew"

[[mods]]
type = "modrinth"
id = "uXXizFIs"
version = "sOzRw3CG"

[[mods]]
type = "modrinth"
id = "YL57xq9U"
version = "zsoi0dso"

[[mods]]
type = "modrinth"
id = "gvQqBUqZ"
version = "E5eJVp4O"

[[mods]]
type = "modrinth"
id = "Bh37bMuy"
version = "KoUrx3jJ"

[[mods]]
type = "modrinth"
id = "vqqx0QiE"
version = "3Smu12Iu"

[[mods]]
type = "modrinth"
id = "Es5v4eyq"
version = "RR1lyQmh"

[[mods]]
type = "modrinth"
id = "AANobbMI"
version = "u1OEbNKx"

[[mods]]
type = "modrinth"
id = "zV5r3pPn"
version = "bb8Z5elg"

[[mods]]
type = "modrinth"
id = "ir8okcEA"
version = "kPsGsZkl"

[[mods]]
type = "modrinth"
id = "defK2XM3"
version = "gDZXNqOx"

[[mods]]
type = "modrinth"
id = "YhmgMVyu"
version = "NSqdh1i9"

[[mods]]
type = "modrinth"
id = "jhl28YkY"
version = "czJc7eUX"

[[mods]]
type = "modrinth"
id = "EsAfCjCV"
version = "b5ZiCjAr"

[[mods]]
type = "modrinth"
id = "lhGA9TYQ"
version = "Wto0RchG"

[[mods]]
type = "modrinth"
id = "BgNRHReB"
version = "TxWM7AW8"

[[mods]]
type = "modrinth"
id = "gc8OEnCC"
version = "4qhBEg6J"

[[mods]]
type = "modrinth"
id = "8shC1gFX"
version = "phATjGhF"

[[mods]]
type = "modrinth"
id = "MpzVLzy5"
version = "M1o6hR2m"

[[mods]]
type = "modrinth"
id = "HXF82T3G"
version = "YPm4arUa"

[[mods]]
type = "modrinth"
id = "zFiY2Go0"
version = "Nw12fcYg"

[[mods]]
type = "modrinth"
id = "uy4Cnpcm"
version = "eRd8PTb9"

[[mods]]
type = "modrinth"
id = "K01OU20C"
version = "nLsCe2VD"

[[mods]]
type = "modrinth"
id = "joEfVgkn"
version = "dmotghAy"

[[mods]]
type = "modrinth"
id = "gu7yAYhd"
version = "YoUTrY6U"

[[mods]]
type = "modrinth"
id = "lz0ymQav"
version = "Cgl4TjDT"

[[mods]]
type = "modrinth"
id = "t1VgucWo"
version = "gC8IvJwh"

[[mods]]
type = "modrinth"
id = "9s6osm5g"
version = "HpMb5wGb"

[[mods]]
type = "modrinth"
id = "SaCpeal4"
version = "LUPOTXbk"

[[mods]]
type = "modrinth"
id = "fnAffV0n"
version = "3MnQb3Tb"

[[mods]]
type = "modrinth"
id = "DNuNq5bb"
version = "khb6eZvR"

[[mods]]
type = "modrinth"
id = "QIt10I7z"
version = "Z6qzb6Wz"

[[mods]]
type = "modrinth"
id = "rYocd2LE"
version = "3dymmAXs"

[[mods]]
type = "modrinth"
id = "nWSeFpQt"
version = "xqZmCXEv"

[[mods]]
type = "modrinth"
id = "tpehi7ww"
version = "EUlNXs9V"

[[mods]]
type = "modrinth"
id = "OVuFYfre"
version = "HBZAPs3u"

[[mods]]
type = "modrinth"
id = "UVtY3ZAC"
version = "DqX0eegg"

[[mods]]
type = "modrinth"
id = "RV1qfVQ8"
version = "i1WCJNIW"

[[mods]]
type = "modrinth"
id = "Ha28R6CL"
version = "N6D3uiZF"

[[mods]]
type = "modrinth"
id = "VZCZSOio"
version = "ITaiugix"

[[mods]]
type = "modrinth"
id = "D53qveoj"
version = "MJ2OF7eg"

[[mods]]
type = "modrinth"
id = "KJe6y9Eu"
version = "2mIvRTNp"

[[mods]]
type = "modrinth"
id = "sTZr7NVo"
version = "LUSqgrjd"

[[mods]]
type = "modrinth"
id = "8BmcQJ2H"
version = "fvT8GY10"

[[mods]]
type = "modrinth"
id = "s3dmwKy5"
version = "lbSHOhee"

[[mods]]
type = "modrinth"
id = "kGP3J2TW"
version = "xWfKx36d"

[[mods]]
type = "modrinth"
id = "y9vDr4Th"
version = "5mQbcYf1"

[[mods]]
type = "modrinth"
id = "nmDcB62a"
version = "NnNX8LBn"

[[mods]]
type = "modrinth"
id = "fPetb5Kh"
version = "9W2MUsnU"

[[mods]]
type = "modrinth"
id = "WBvnqHfV"
version = "TRMapjpU"

[[mods]]
type = "modrinth"
id = "MPCX6s5C"
version = "pznwoEHz"

[[mods]]
type = "modrinth"
id = "ccKDOlHs"
version = "JB1fLQnc"

[[mods]]
type = "modrinth"
id = "tagwiZkJ"
version = "Ng5Y6KVo"

[[mods]]
type = "modrinth"
id = "J9pKOkxP"
version = "cEF2AxxA"

[[mods]]
type = "modrinth"
id = "aaRl8GiW"
version = "Ef7P6Rb7"

[[mods]]
type = "modrinth"
id = "3NCrJdj3"
version = "QtkC5plA"

[[mods]]
type = "modrinth"
id = "gnwGOmBf"
version = "Z6zil2J0"

[[mods]]
type = "modrinth"
id = "KDvYkUg3"
version = "rfFqJDcN"

[[mods]]
type = "modrinth"
id = "nfn13YXA"
version = "aWzTESNC"

[[mods]]
type = "modrinth"
id = "aTaCgKLW"
version = "jrC1TCfF"

[[mods]]
type = "modrinth"
id = "ItTQpuBn"
version = "fcg0BOwC"

[[mods]]
type = "modrinth"
id = "LN9BxssP"
version = "euSlaAtA"

[[mods]]
type = "modrinth"
id = "rOUBggPv"
version = "SZOjxftk"

[[mods]]
type = "modrinth"
id = "3eMENr4V"
version = "CNwZZ4FD"

[[mods]]
type = "modrinth"
id = "kkmrDlKT"
version = "XNtIBXyQ"

[[mods]]
type = "modrinth"
id = "8oi3bsk5"
version = "MuJMtPGQ"

[[mods]]
type = "modrinth"
id = "54eqfZSC"
version = "5A24T8JD"

[[mods]]
type = "modrinth"
id = "RJcwF5bg"
version = "azmCiYpi"

[[mods]]
type = "modrinth"
id = "rlloIFEV"
version = "i6cd1S6S"

[[mods]]
type = "modrinth"
id = "5aaWibi9"
version = "JagCscwi"

[[mods]]
type = "modrinth"
id = "kpMfA312"
version = "LGF8VScD"

[[mods]]
type = "modrinth"
id = "OhduvhIc"
version = "1NZqjOaM"

[[mods]]
type = "modrinth"
id = "OMiCHIwt"
version = "ByAkqZD1"

[[mods]]
type = "modrinth"
id = "RiN8rDVs"
version = "mPmeykPR"

[[mods]]
type = "modrinth"
id = "31zVNrFa"
version = "9fdKSEzJ"

[[mods]]
type = "modrinth"
id = "1bokaNcj"
version = "Vqkdzsyt"

[[mods]]
type = "modrinth"
id = "NcUtCpym"
version = "hT5eHHLt"

[[mods]]
type = "modrinth"
id = "1eAoo2KR"
version = "o3cDn8Vp"

[[mods]]
type = "modrinth"
id = "Ua7DFN59"
version = "9aZPNrZC"

[[mods]]
type = "modrinth"
id = "Dfu00ggU"
version = "72UkhXm7"

[[mods]]
type = "modrinth"
id = "o1C1Dkj5"
version = "fQ7EjDPE"

[[mods]]
type = "modrinth"
id = "2BwBOmBQ"
version = "zpUYcjIg"

[[mods]]
type = "modrinth"
id = "z9Ve58Ih"
version = "uiGCmR8O"

[[mods]]
type = "modrinth"
id = "Z2mXHnxP"
version = "gxBGYcIL"

[[mods]]
type = "modrinth"
id = "3dT9sgt4"
version = "TGK6gpeO"

[[mods]]
type = "modrinth"
id = "kidLKymU"
version = "uYZShp1p"

[[mods]]
type = "modrinth"
id = "t5FRdP87"
version = "bdpPtvTn"

[[mods]]
type = "modrinth"
id = "cs7iGVq1"
version = "geZa9lJS"

[[mods]]
type = "modrinth"
id = "w7ThoJFB"
version = "WmVN03jQ"

[[mods]]
type = "modrinth"
id = "x3HZvrj6"
version = "zxxPmIks"

[[mods]]
type = "modrinth"
id = "uNRoUnGT"
version = "ZYE0xW87"
