name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cd433c38e92c07502494724fb9c6a4fdc24ad826ec01bd679fff0d65b95636db"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
