name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a7b3154d61a7d8caf5bf6918cf586726e03f1359d858f8a6bcaa14195648afa7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
