name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6b9cc03d191c602fecb187032c8d409bdfb0c02de9f4f0cadee5242b99716e76"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
