hash-format = "sha256"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "bd0848389894ffe9850efb36210060ff0ac3cc31c74af7f80a897de05df4caa2"
metafile = true

[[files]]
file = "mods/advanced-reborn.pw.toml"
hash = "faa778c39d17a031bb6c8c59d26286e286ba09d36528e7c98d358faf84be7bb9"
metafile = true

[[files]]
file = "mods/adventurez.pw.toml"
hash = "b83be649099ba1f38968a9d331acbfb36e6a45863c290a0ddc8f55b010d74422"
metafile = true

[[files]]
file = "mods/aether.pw.toml"
hash = "e71c04679ff75573cd8ef1003eb167830f794b8979f2bdd3c99d28793f2918b0"
metafile = true

[[files]]
file = "mods/alloy-forgery.pw.toml"
hash = "2adf518c92809d9a8cb8c1bbb8f40f8d631a5702ccbcc4ee617a9365dcf48a4e"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "17fc9c6cab5ae0ea6973440f143ad6ffa4e5d373749c80077b631dbbe4df3f3b"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "1102440dd2533ba3a154419bb95ff1f81b858201eb0c44d2a2eea486c74e565a"
metafile = true

[[files]]
file = "mods/bclib.pw.toml"
hash = "2195df15cde85a2ec76bb9abec09597efc304e3fd1bca08fd4027ba053d86661"
metafile = true

[[files]]
file = "mods/betterend.pw.toml"
hash = "f15c8cd06fb1e7ececdb01942d2b86a60a0eebaf9d88f9c3defda77c0a115496"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "7d1815ec4f2098c4de8b01494373d84da8a5104accd5ae028a2a020595646082"
metafile = true

[[files]]
file = "mods/betternether.pw.toml"
hash = "2cf79d151d64ae6a26e037bc883c457eaec6089685df02c7474a1d130f6daaa7"
metafile = true

[[files]]
file = "mods/biomes-o-plenty.pw.toml"
hash = "ddbb4bf26d15027847e52f5b30479470299b9a8c687697309f0535d658b9944b"
metafile = true

[[files]]
file = "mods/blockus.pw.toml"
hash = "9215ff2d8210dbea85c4e1139d566bd504bac50cb8e0396e7475079cb3270bd7"
metafile = true

[[files]]
file = "mods/bookshelf-lib.pw.toml"
hash = "0b775ba140d7797e2456b8b09c7162f6a81de22abb7feb2e8437847cefd86d0a"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0c345c80310a4bd58c757e43d6060338a85d34eaffcb674a6e9cbf22ecbc9cb8"
metafile = true

[[files]]
file = "mods/carry-on.pw.toml"
hash = "6a492387f6348192bcb9e2ee15f9be142100648ce60080a75f980185cb66ee13"
metafile = true

[[files]]
file = "mods/cc-tweaked.pw.toml"
hash = "252d64d837d274aa46b00729f136d5900a5fb029f8c25f11f280a9b34da6add1"
metafile = true

[[files]]
file = "mods/charm-forked.pw.toml"
hash = "a1c4736d7ab8e14ad7f537197187fe9f6a67388de80bb634a21c296cda070326"
metafile = true

[[files]]
file = "mods/chunk-loaders.pw.toml"
hash = "4afbe5d16695aa241c61c67d3cc3e0b1259872f3f1380241eeb51176c78fe038"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "446c173c87b7908daee86b0dee89c6b628c77beb7a0bc091ff5252b7c0062080"
metafile = true

[[files]]
file = "mods/comforts.pw.toml"
hash = "0d10973de4466406d116a7c0d976c7c7830e65510ad06b6c83e72b0310e09ad4"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
hash = "d056036f71ac0fe66147f415e0142c1fd8889c065b7f1e5880ad3d46c583136f"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-ancient-city-overhaul.pw.toml"
hash = "e811185f1b2c3d26c5bb3dfcab59d1e86dee35815f7f25a10efec48cf4f48b4e"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-pillager-outpost-overhaul.pw.toml"
hash = "bee4f2f4f7abd7c1f14f3f4690ed5e26f18cb732b962f2f5b4b6c0cd522662b9"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-stronghold-overhaul.pw.toml"
hash = "54d67580e5ce1338e9813fe571338fcb7503989801db66fd901a997f4220bc29"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns-swamp-hut-overhaul.pw.toml"
hash = "834584cac85ff31f7e76527389f7fbe3358eb1fd5ae8ed2c9146032bda8b8717"
metafile = true

[[files]]
file = "mods/dungeons-and-taverns.pw.toml"
hash = "447ec530620e3c0da62316cb3358e43c15132084aab22ba992fefac199ca92a9"
metafile = true

[[files]]
file = "mods/ebe.pw.toml"
hash = "b1f89407254a20cde6c60994a6315bd841b7f562669a1d29b436ec97463ff2ae"
metafile = true

[[files]]
file = "mods/enchantment-descriptions.pw.toml"
hash = "f7bb88ccf59b362d533cef59b28b0cab3ef017ad7462dfbe0daae2a0aa30032e"
metafile = true

[[files]]
file = "mods/explorers-compass.pw.toml"
hash = "9642962bbcc8bfd0fc299df9858ba7e9ff8d25a6d69a6df976577d9cb219f442"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "49884f2d7db0e731facf0aa70cf2038dd513624c450cba773a8ca7a47e53953b"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabric-seasons-natures-spirit-compat.pw.toml"
hash = "5b9f29791a13391eac2bf6f4998480421ab471a4e52b5344a5ee70982488a76f"
metafile = true

[[files]]
file = "mods/fabric-seasons-terralith-compat.pw.toml"
hash = "751b5e7213feb2072ee728327dcbb58134add5c5b0441c866dc0aa9fa1255e3b"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "d40faa8d75ec7b4741146b033dca1d47368868985da3dcc6dc32fd9def5841d9"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "1d5799cd3b6ea714602c18546b99ba894e7511835b77803304792468fb7ee187"
metafile = true

[[files]]
file = "mods/fwaystones.pw.toml"
hash = "7308954ec68ead6840f1c5774a7b1465c0f8c8f8cf110ee8ba77952229930ffa"
metafile = true

[[files]]
file = "mods/geckolib.pw.toml"
hash = "fe2682e6dbdd4350863e1fcd3f5f211fb437cf7791539bedd50779745beb5232"
metafile = true

[[files]]
file = "mods/glitchcore.pw.toml"
hash = "a104f2f6044d43bbc5a5badc6f589b2f6f5a1b9c9e47e00dfbad5061aa3b51f4"
metafile = true

[[files]]
file = "mods/immersive-machinery.pw.toml"
hash = "4f7727c49e623864c1297e4c7a16eefb33893119865b7e96787da9c5119c8e8b"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "5284f6d141a990f4ea021c12b851e07102f5cb22743cf7b33be6ad2eb4c8d3f5"
metafile = true

[[files]]
file = "mods/item-collectors.pw.toml"
hash = "bfe0198a67fc0a47274baf8a530b82e62eb2c52136ccbd77e8f9853446583053"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5564dbbe8adc0ba450afc6a1c3eef82f183a53ede5f3b1de0bc6ca320aadc5e9"
metafile = true

[[files]]
file = "mods/modernfix.pw.toml"
hash = "b9651d06e56ad51c1cdcf4b03b6a34328b7dc941f263ff92b189ee26a47cc224"
metafile = true

[[files]]
file = "mods/natures-compass.pw.toml"
hash = "f53b91397b8a969e843af8772db448ab1c9bc556233a3b26266c52cfa77950fe"
metafile = true

[[files]]
file = "mods/natures-spirit.pw.toml"
hash = "50d4c9a5a97937e4d9309b28c3cb283832eca78a6425644198bfd8dbf49d3bdd"
metafile = true

[[files]]
file = "mods/not-enough-animations.pw.toml"
hash = "7548976b015cdc8bfb7df92e09ff6744accd01ea722dcfd7f842d51bdeaf73a2"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "60a3d23eb73106ecb6ba5a391d4539e3557cbd9b1f3611a2de08052155d78b3a"
metafile = true

[[files]]
file = "mods/polymorph.pw.toml"
hash = "8a64fdd5384cd26c91475a423f3bec24dd4d98796df7683a5070ef105d421ba4"
metafile = true

[[files]]
file = "mods/potentials.pw.toml"
hash = "b9c832ad73ef4bbe1b4f604fbbbaab7610f908703e1a2fd027ca3758127fa4ae"
metafile = true

[[files]]
file = "mods/prickle.pw.toml"
hash = "122659d423e8fe5c47b4121bf382e5ceea0ea2c644cd0a08d577cf58ef55d495"
metafile = true

[[files]]
file = "mods/reborncore.pw.toml"
hash = "e5c1e399e09df87b7126f16ea3097c6f0c5ea47d06a52fc696a68319e18e866f"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/refined-storage-quartz-arsenal.pw.toml"
hash = "5032fe594fbe66cabea1f71ae850c6a69389b9653a21e342f6d1aaf071d5769e"
metafile = true

[[files]]
file = "mods/refined-storage.pw.toml"
hash = "bd6908e31ff73f14ffb53be9b4895fc27a01e8e9fe441455c976803eec31d291"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "d22546ad55b555931eb527f163b3564e00c12c7dc8101378b87447dfcc8e0652"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "90d1f4ee70f4b208b623af04b48be8fd5b98b411cbd4d9d0a5b23d07ba99c1e4"
metafile = true

[[files]]
file = "mods/sodium-extras.pw.toml"
hash = "247d0c160732895f6bc4a3cf0f0ccf74f55fc9ea67800e87495b8d817093fbbe"
metafile = true

[[files]]
file = "mods/sodium-options-api.pw.toml"
hash = "461adc31ce2b89cafc5ad2e846b482c68529231ac1d907e39ec62458b22e6b3e"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "be0c8881821da897824770b2a71f0f3765a233eda69b295fa5b92ffe8a25014c"
metafile = true

[[files]]
file = "mods/stellaris.pw.toml"
hash = "2fb127dfd1760b6e255dfb5bcce4148782c647cfc8ed5d4d748262ff4fe84ed4"
metafile = true

[[files]]
file = "mods/supermartijn642s-config-lib.pw.toml"
hash = "8e009ac87710fbd8f5990285d36ab2b4755e932664ca1bcb9cdfac116d6e3b6d"
metafile = true

[[files]]
file = "mods/supermartijn642s-core-lib.pw.toml"
hash = "04d5cccae8671610cfcff582f7c1b490ba09622a476b53421cd078eb322f27ae"
metafile = true

[[files]]
file = "mods/techreborn.pw.toml"
hash = "9025e5c9f5032ed316208c509e44f7f3e93d3eb5f3a9379a78eda815ff643acc"
metafile = true

[[files]]
file = "mods/terrablender.pw.toml"
hash = "e35593590fe988653baebae4638f6c93b5d822351274955cc1288b34fe5429fe"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "da7ee99189ad35aac094919fe33cac647d98533b23c228f10d4811f08989e2b8"
metafile = true

[[files]]
file = "mods/totw-modded.pw.toml"
hash = "f7c14947970c8de4dfbaf32e48cba47cf504fccaf89562d078f7eebab45d1e6a"
metafile = true

[[files]]
file = "mods/towers-of-the-wild-modded-extra-towers.pw.toml"
hash = "20e54de08a5edc6ad57cd6856279b99ccff9d52b671438afa44cde6219db8dc7"
metafile = true

[[files]]
file = "mods/travelersbackpack.pw.toml"
hash = "e657896d405e82e4539be5c1562f27c666a9d5ca8dad5d30052a402c4916766e"
metafile = true

[[files]]
file = "mods/trinkets.pw.toml"
hash = "860812150cb54f0d9ee1bce7b72798b6cc5f752bb05709f0c60231d054ec281d"
metafile = true

[[files]]
file = "mods/universal-grid.pw.toml"
hash = "738b7fed7cbbdff93a22e19637e40334fcb4b8e99520e2d1d7ecfb167293eb7d"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "79a914c22a29620290a146689b8f37fa3c707c590a1edcca9665eff659b1562e"
metafile = true

[[files]]
file = "mods/voidz.pw.toml"
hash = "bded47bc3fe99b3bbec5dd34cf2d432f4d0dfaa048644933dd17347d324b3d5f"
metafile = true

[[files]]
file = "mods/worldweaver.pw.toml"
hash = "d3dccbd68486d3b35054b5a716051fa01a916d808a2aa78a0ada72b31f08c428"
metafile = true

[[files]]
file = "mods/xaeros-minimap-and-waystones-compatibility.pw.toml"
hash = "4b6519192930987440f9d875bbdad35872b8f95c237ce29d522336c13e1f8252"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "120b1b5e775ec88fb6b6a3c11f4d3685a2b28d0badfb73b3606f946599d6b587"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "80d14aa6af38caa8f61f2bd1e98744f6aeda9c0701684ed80422ded03ebab640"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "af20070dd9497817a83162c17b181a0a44f7213ea302d059a81c5aed02d0c877"
metafile = true

[[files]]
file = "mods/yungs-api.pw.toml"
hash = "4d98bdba90cdeae788a747bb6fe7d438ba49fdc4eb67c38d4573304eec4a2ef8"
metafile = true

[[files]]
file = "mods/yungs-better-caves.pw.toml"
hash = "57c6e291ce10527ca8672b0ab508dea77afa067b7ec5daf772904cf2105e5e1e"
metafile = true

[[files]]
file = "mods/yungs-better-dungeons.pw.toml"
hash = "ffcf32caf3dda8f05adb109dc86c477cf1bb768bac6232bc5bcf0d60a7861bcb"
metafile = true

[[files]]
file = "mods/yungs-better-end-island.pw.toml"
hash = "a9f7ce3ef90cd500e451ff6534d42f0532150d5f207c974468295fbe8c7b5a47"
metafile = true

[[files]]
file = "mods/yungs-better-jungle-temples.pw.toml"
hash = "9ebe3f899af40f9bec87d76c2c3dc85004278d30165fcbc0020a11d47da5d35e"
metafile = true

[[files]]
file = "mods/yungs-better-nether-fortresses.pw.toml"
hash = "a33c822c6525c8b708475161e263cb18883332383a6b25e2b5915623f0e5b85c"
metafile = true

[[files]]
file = "mods/yungs-better-ocean-monuments.pw.toml"
hash = "15ef858f138af87eb7376988107cb6f61bccf578c4c8bcca44a473a0ca128e41"
metafile = true

[[files]]
file = "mods/yungs-better-strongholds.pw.toml"
hash = "66e4fca8e34915da64ec530a9153500271016e2086752a7f196f71a5c6135d84"
metafile = true

[[files]]
file = "mods/yungs-better-witch-huts.pw.toml"
hash = "1bd0ba1128e6ae3f926298c2ffe33180cca75362fae3bd92146d43977297f01c"
metafile = true

[[files]]
file = "mods/yungs-cave-biomes.pw.toml"
hash = "57ae99f727e3fcd7a1abbc624bf14cafa5f092f2082dcf3edc609289efb25c15"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "2709ce9505c0a00b9406f83eb4bc158f5cad773b96fc3826c88dca45d65876cd"
metafile = true

[[files]]
file = "resourcepacks/xaeros-minimap-aether-icons.pw.toml"
hash = "817c2c9d91adc2b1b0fa97d96708b613cae67dff5f123d4b26a5a57b52cf3137"
metafile = true
