name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40f0b0cbd5edf6b6f952a9c6cfc7b39b5b8a6777a087567aeec1cc141b012120"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
