name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39d4ada0d34c39be5433726c326f83ebd7b29eeae6b1305517fe87d234a2e0ff"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
