name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "041c00455250d30151d74d1bc6bd552814b4def1c93998f60ff6858ef45188c7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
