name = "MNT-SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dc67e2a7b93e11bd0a3fa18af8c906f7072f8ed13746e18ff0622d84aa652c25"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
