name = "mnt-smp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "211134e3a46d6ef1e5abdc018b94064b0d906cb3b52da33828eddf9b7cd03c53"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
