name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "41808678b1975bad5f7084df6d747c03c1a90d0f5386010c2ff6aa0212a2480d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
