name = "MNT-SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "19ff75d0c7159ea402405b9636917103707555522c971e069a8e1c45b9aeed85"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
