name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ffe7bf256fda63336bccad8680ef64b18cc7c4f912494a222430621f64d8fff4"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
