name = "mnt-smp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "511fd291ef046985de44f6ba85a860ef3842f65c94b6cbbb409f1370ba28eb9e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
