name = "mnt-smp"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "93cc54ac4dfeb45f1fc57b11553fc92f3e5349bf536df2c5c74e2e78f07ea96d"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
