name = "MNT SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7df90e30861d3931512e05328b70f1111820695c9bdfd899fc62b31f0f1eb1e0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
