name = "MNT-SMP"
author = "Mega"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b2741ab52ee9f437f605c2340369135b72df53b35f0b4cf90456594d37824598"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
